.circleci/config.yml
Change the circleCi configuration so work under the corporate proxy is possible.
=> Update CircleCi configuration file

scripts/README.md, scripts/api_call.sh
* subjectName added as a param (on create endpoint)
* updated readme about api_call script
This PR is already reviewed: https://github.com/NervanaSystems/inferno-platform/pull/236
=> BIP2-198 api_call changes

scripts/README.md, scripts/api_call.sh
Fixing minor mistake in CERT parameter description in api_call.sh
=> Readme and help fix in api_call.sh

management/management_api/config.py, management/management_api/endpoints/endpoint_utils.py, management/management_api/endpoints/endpoints.py, management/test/test_auth/test_endpoints_auth.py, management/test/test_endpoints/test_endpoints.py, tests/conftest.py, tests/management_api_tests/endpoints/test_endpoints.py
Summary of changes:
- add warning about model existence during endpoint creation
- update unit tests
=> Create endpoint should verify if model exist - show warning

examples/grpc_client/requirements.txt, tests/config.py, tests/conftest.py, tests/e2e_tests/config.py, tests/e2e_tests/inference_endpoints/test_inference_endpoints.py, tests/management_api_tests/endpoints/endpoint_utils.py, tests/management_api_tests/endpoints/test_endpoints.py, tests/run_test.sh
Summary of changes:
- add asserts of subject name in e2e test for endpoint creation
- move updating of subject name test to functional tests
=> Fix test for subject name change

docs/exampleinstallation.md
Signed-off-by: Sakari Poussa <sakari.poussa@intel.com>
=> Update incorrect document link

examples/grpc_client/grpc_client.py, scripts/imm
Changes:
- fixed transpose
- optional parameters for __./imm run-inference__: input_name, output_name, transpose_input
=> Optional parameters for running inference via IMM CLI

scripts/README.md, scripts/requirements.txt
Changes:
- added requirements.txt in scripts directory
=> Requirements in scripts directory

examples/grpc_client/grpc_client.py
also corrected transpose operation
=> arbitrary batch size and iterations

examples/grpc_client/grpc_client.py, management/management_api/schemas/elements/models.py, management/management_api/schemas/uploads.py, management/management_api/upload/multipart.py, management/management_api/upload/multipart_utils.py, management/management_api/utils/routes.py, scripts/README.md, scripts/model_upload.py, scripts/model_upload_cli.py, scripts/requirements.txt, tests/conftest.py, tests/e2e_tests/inference_endpoints/test_inference_endpoints.py
In order to support other model resources than frozen graph (especially saved model with variables) there's upload dir feature needed in uploading scripts. Also, there will be possible to pass tarballs to upload scripts.
=> Support not only frozen graph

scripts/prepare_test_env.sh
* changed REQUEST_CA_BUNDLE to proper REQUESTS_CA_BUNDLE
* changed MANAGEMENT_API_CERT_PATH to proper MANAGEMENT_CA_CERT_PATH
=> Fixed envs names in prepare_test_env

helm-deployment/crd-subchart/values.yaml, helm-deployment/management-api-subchart/values.yaml, installer/README.md, installer/crd/install.sh, installer/install.sh, installer/main.sh, installer/management-api/install.sh, installer/minio/install.sh, installer/minio/minio_ing_tmpl.yaml, installer/utils/show_help.sh, tests/deployment/deployment_crd.sh, tests/deployment/deployment_management_api.sh
Manually tested using Scaleway S3 and AWS S3.
=> Add '-t' option to installer help, enable external minio/s3 in installer

.circleci/config.yml
* changed due to missing jessy deb packages
=> changed python3.6.6-jessy-browsers images to python3.6.6-browsers

installer/README.md, installer/install.sh, installer/main.sh
=> enable disabling validation at the end of the installer

scripts/imm_utils.sh
=> fix IMM_CONFIG_PATH in utils-imm

.circleci/config.yml, installer/default_tenant.sh, management/management_api/authenticate/authenticate.py, management/management_api/tenants/tenants.py, management/management_api/tenants/tenants_utils.py, scripts/imm_tests.bats, tests/e2e_tests/inference_endpoints/test_inference_endpoints.py, tests/management_api_tests/tenants/test_tenants.py
It's first part of changes requested in #87 .
=> change tenant endpoint output to json format

.circleci/scripts/clean_up_gke.sh, .circleci/scripts/clean_up_kops.sh, installer/uninstaller.sh, scripts/prepare_test_env.sh
Addressing https://github.com/IntelAI/inference-model-manager/issues/78
As we want only authenticated users to be able to uninstall the platform, whole removal process should be stopped if user does not have a valid token. Uninstall shall be fully completed or not begin in the first place.
=> Uninstall possible for logged users only.

management/management_api/upload/multipart.py, scripts/model_upload.py
Addressing https://github.com/IntelAI/inference-model-manager/issues/87
=> Change multipart upload output to JSON format

management/management_api/servings/servings.py, management/management_api/servings/servings_utils.py, tests/management_api_tests/servings/test_servings.py
Addressing https://github.com/IntelAI/inference-model-manager/issues/87
=> Change serving output to JSON format

management/README.md, management/management_api/config.py
=> Update README for JSON output format
